# Happy Coding!

service: slsblogpoc

provider:
  name: aws
  runtime: nodejs4.3
  apiKeys:
    - SLSBLOGKEY
package:
  exclude:
    - rust/
    - admin/

functions:
  home:
    handler: main/handler.main
    events:
      - http:
          method: GET
          path: home
          response:
            headers:
              Content-Type: "'text/html'"
            template: $input.path('$')
  post:
    handler: page/handler.main
    events:
      - http:
          method: GET
          path: page/{id}
          response:
            headers:
              Content-Type: "'text/html'"
            template: $input.path('$')
  new:
    handler: new/handler.main
    events:
      - http:
          method: GET
          path: new
          response:
            headers:
              Content-Type: "'text/html'"
            template: $input.path('$')

resources:
  Resources:
    AuthorTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: "Author"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "Author"
            KeyType: "HASH"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: "slsblog-authors"
    TagTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: "Tag"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "Tag"
            KeyType: "HASH"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: "slsblog-tags"
    PostTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: "postId"
            AttributeType: "N"
          - AttributeName: "Author"
            AttributeType: "S"
          - AttributeName: "Status"
            AttributeType: "S"
          - AttributeName: "Snippet"
            AttributeType: "S"
          - AttributeName: "Title"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "postId"
            KeyType: "HASH"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: "slsblog-posts"
        GlobalSecondaryIndexes:
          - IndexName: "slsblog-author-index"
            KeySchema:
              - AttributeName: "Author"
                KeyType: "HASH"
              - AttributeName: "postId"
                KeyType: "RANGE"
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
            Projection:
              NonKeyAttributes:
                - "Snippet"
                - "Title"
              ProjectionType: "INCLUDE"
          - IndexName: "slsblog-status-index"
            KeySchema:
              - AttributeName: "Status"
                KeyType: "HASH"
              - AttributeName: "postId"
                KeyType: "RANGE"
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
            Projection:
              NonKeyAttributes:
                - "Snippet"
                - "Title"
              ProjectionType: "INCLUDE"
