[package]
name = "slsblogpage"
version = "0.1.0"
authors = ["ec2-user"]
license = "MIT"

[lib]
name = "slsblogpage"
crate-type = ["dylib"]

[dependencies]
neon = "0.1"
markdown = "0.1"
horrorshow = "0.5.6"
