[package]
name = "home"
version = "0.1.0"
authors = ["Orion Free <orion@orionfree.com>"]
license = "MIT"
build = "build.rs"

[lib]
name = "home"
crate-type = ["dylib"]

[build-dependencies]
neon-build = "0.1.18"

[dependencies]
neon = "0.1.18"
handlebars = "0.25.*"
rustc-serialize = "*"
glob = "*"
